language: node_js
node_js:
  - "node"

after_success:
  - git config --global user.name "analoguemachine"
  - git config --global user.email "analoguemachine@users.noreply.github.com"
  - git remote rm origin
  - git remote add origin https://analoguemachine:${GH_TOKEN}@github.com/analoguemachine.github.io.git
  - npm run deploy